import urllib.parse

# Brief: get netgraph and switch ID and port where a specific IP is connected to;
def _get_host_location(netgraph: dict, host_ip: str):
    host = netgraph.get("hosts", {}).get(host_ip)
    if not host:
        raise KeyError(f"Host {host_ip} não encontrado no netgraph. O ONOS ainda não o descobriu!")

    locs = host.get("locations") or []
    if not locs:
        raise KeyError(f"Host {host_ip} existe, mas não possui localização (porta) conhecida.")

    # Retorna (deviceId, port) do primeiro local conhecido
    element_id = locs[0]["elementId"] 
    port = str(locs[0]["port"]) 
    return element_id, port


def _flow_body(src_ip, dst_ip, out_port, device_id, priority=40000):
    return {
        "appId": "org.onosproject.core",
        "priority": priority,
        "isPermanent": "true",
        "deviceId": device_id,
        "treatment": {"instructions": [{"type": "OUTPUT", "port": str(out_port)}]},
        "selector": {"criteria": [
            {"type": "ETH_TYPE", "ethType": "0x0800"},
            {"type": "IPV4_SRC", "ip": f"{src_ip}/32"},
            {"type": "IPV4_DST", "ip": f"{dst_ip}/32"}
        ]}
    }


# Brief: discover which src_dev port takes to dst_dev
def get_port_between_switches(onos, src_dev, dst_dev):
    res = onos._make_request("GET", "/links")
    links = (res.get("content") or {}).get("links") or []
    for l in links:
        if l['src']['device'] == src_dev and l['dst']['device'] == dst_dev:
            return l['src']['port']
    return None


# Brief: install flow rules following list of tuples [(i, j), (j, k)]
def install_custom_path(onos, netgraph, client_ip, server_ip, path_indices, estados, device_map):
    responses = []
    
    # Install rules on intermediate switches (OVS <-> OVS)
    for (u_idx, v_idx) in path_indices:
        src_sw = device_map[estados[u_idx]]
        dst_sw = device_map[estados[v_idx]]
        
        # Get out_port from curr switch onto the next one
        port = get_port_between_switches(onos, src_sw, dst_sw)
        
        body = _flow_body(client_ip, server_ip, port, src_sw)
        responses.append(onos._make_request("POST", f"/flows/{urllib.parse.quote_plus(src_sw)}", data=body))

    # Install rule on final switch to communicate with the host
    last_sw_idx = path_indices[-1][1] # get last path switch
    last_sw_id = device_map[estados[last_sw_idx]]
    
    # Get which port the server is pluged to
    host_data = netgraph['hosts'].get(server_ip)
    final_port = host_data['locations'][0]['port']
    
    body_final = _flow_body(client_ip, server_ip, final_port, last_sw_id)
    responses.append(onos._make_request("POST", f"/flows/{urllib.parse.quote_plus(last_sw_id)}", data=body_final))

    return responses


# Brief: Installs the forward path (Client -> Server) and the return path (Server -> Client) 
# based on the hops generated by the QoE algorithm.
def install_bidirectional_custom_path(onos, netgraph, client_ip, server_ip, path_indices, estados, device_map, priority=40000):
    resps = []
    
    # Install on hop switches
    for (u_idx, v_idx) in path_indices:
        src_sw = device_map[estados[u_idx]]
        dst_sw = device_map[estados[v_idx]]
        out_port = get_port_between_switches(onos, src_sw, dst_sw)
        
        if not out_port:
            raise ValueError(f"Link corrupted: {src_sw} -> {dst_sw}")

        body = _flow_body(client_ip, server_ip, out_port, src_sw, priority)
        resps.append(onos._make_request("POST", f"/flows/{urllib.parse.quote_plus(src_sw)}", data=body))


    # Final switch forwards the packet to the Server host
    last_sw_id = device_map[estados[path_indices[-1][1]]]
    srv_sw, srv_port = _get_host_location(netgraph, server_ip)
    resps.append(onos._make_request("POST", f"/flows/{urllib.parse.quote_plus(srv_sw)}", 
                 data=_flow_body(client_ip, server_ip, srv_port, srv_sw, priority)))

    # Return path: invert hop logic
    for (u_idx, v_idx) in reversed(path_indices):
        src_sw = device_map[estados[v_idx]] # inverts src/dst of the link
        dst_sw = device_map[estados[u_idx]]
        out_port = get_port_between_switches(onos, src_sw, dst_sw)
        
        if not out_port:
            raise ValueError(f"Link corrupted: {src_sw} -> {dst_sw}")

        body = _flow_body(server_ip, client_ip, out_port, src_sw, priority)
        resps.append(onos._make_request("POST", f"/flows/{urllib.parse.quote_plus(src_sw)}", data=body))

    # Last switch delivers to host Cliente
    cli_sw, cli_port = _get_host_location(netgraph, client_ip)
    resps.append(onos._make_request("POST", f"/flows/{urllib.parse.quote_plus(cli_sw)}", 
                 data=_flow_body(server_ip, client_ip, cli_port, cli_sw, priority)))

    return resps


def remove_old_flows(onos, client_ip, server_ip, device_map):
    print(f" [LIMPEZA] Varrendo e apagando regras antigas para {client_ip} <-> {server_ip}...")
    
    for uf, device_id in device_map.items():
        # Get all frules installed inside a switch
        res = onos._make_request("GET", f"/flows/{urllib.parse.quote_plus(device_id)}")
        
        if not res or "flows" not in res:
            continue
            
        for flow in res["flows"]:
            # Ignore default ONOS frules (ARP, LLDP) and focuses only in IPv4 traffic
            criteria = flow.get("selector", {}).get("criteria", [])
            
            ips_in_flow = []
            for c in criteria:
                if "ip" in c:
                    # Removes /32 mask
                    clean_ip = c["ip"].split("/")[0]
                    ips_in_flow.append(clean_ip)
                    
            # If frule contains both client IP and server IP, it's the one to be removed
            if client_ip in ips_in_flow and server_ip in ips_in_flow:
                flow_id = flow.get("id")
                onos._make_request("DELETE", f"/flows/{urllib.parse.quote_plus(device_id)}/{flow_id}") # delete frule
                print(f"  Regra {flow_id} aniquilada no Switch {device_id}")
